syms gamma eta k y

t1 = gamma*(y-eta*(k+1));

f_0 = (gamma^2 * sqrt(2*gamma) * ...
    (gamma * (y - eta*(k+1)) * (-gamma*eta*(k+1) + gamma*y + 2) ...
    - 2*(exp(gamma * (y - eta*(k+1))) - 1))) / (2 * gamma^3);

f_1 = gamma^2 * sqrt(2*gamma) * ...
    (gamma * eta + gamma * eta * k + exp(gamma*(y-eta*(k+1))) ...
    - gamma * y -1) / (gamma^2);


f_2 = (- sqrt(2*gamma) * 0.5) * ...
    (t1 * (-gamma*eta*(k+1)+gamma*y+2) - 2 * (exp(t1)-1)) ...
    + (- sqrt(2*gamma) * (exp(t1)-1)) ...
    + (- sqrt(2*gamma) * (gamma*eta + gamma*eta*k ...
    + exp(t1)*(gamma*eta*(k+1)-gamma*y+2)-gamma*y-2));


f_3 = sqrt(2*gamma) * exp(t1) ...
    + sqrt(2*gamma) * 0.5 * (y-eta*k) * (2*exp(t1)*(-gamma*eta*(k+1)+gamma*y-3) ...
    +t1*(-gamma*eta*(k+1)+gamma*y+4)+6) ...
    -sqrt(2*gamma) * (exp(t1)*(-gamma*eta*(k+1)+gamma*y-1)+1) ...
    + sqrt(2*gamma) * 0.5 * (2*gamma*eta*(k+1) ...
    +exp(t1)*(t1*(-gamma*eta*(k+1)+gamma*y-4)+6)-2*gamma*y-6);



sigma_00 = int(f_0^2, y, k*eta, eta*(k+1));
sigma_01 = int(f_0*f_1,y, k*eta,eta*(k+1));
sigma_02 = int(f_0*f_2,y, k*eta,eta*(k+1));
sigma_03 = int(f_0*f_3,y, k*eta,eta*(k+1));
sigma_11 = int(f_1^2, y, k*eta, eta*(k+1));
sigma_12 = int(f_1*f_2, y, k*eta, eta*(k+1));
sigma_13 = int(f_1*f_3, y, k*eta, eta*(k+1));
sigma_22 = int(f_2^2, y, k*eta, eta*(k+1));
sigma_23 = int(f_2*f_3, y, k*eta, eta*(k+1));
sigma_33 = int(f_3^2, y, k*eta, eta*(k+1));


latex(simplify(sigma_23))
